vim.keymap.set("n", "<leader>f", vim.lsp.buf.format, {})
local telescope = require("telescope.builtin")
vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex, {})
vim.keymap.set("n", "<leader>pf", telescope.find_files, {})
vim.keymap.set("n", "<leader>ps", function()
    telescope.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set("i", "jj", "<Esc>", { noremap = true })
vim.keymap.set("n", "<leader>gs", "<cmd>lua require('gitsigns').stage_hunk()<cr>", { desc = "Stage Hunk" })
vim.keymap.set("n", "<leader>gu", "<cmd>lua require('gitsigns').undo_stage_hunk()<cr>", { desc = "Undo Stage Hunk" })
vim.keymap.set("n", "<leader>gr", "<cmd>lua require('gitsigns').reset_hunk()<cr>", { desc = "Reset Hunk" })
vim.keymap.set("n", "<leader>gp", "<cmd>lua require('gitsigns').preview_hunk()<cr>", { desc = "Preview Hunk" })
vim.keymap.set("n", "<leader>gb", "<cmd>lua require('gitsigns').blame_line()<cr>", { desc = "Blame Line" })
vim.keymap.set("n", "<leader>gf", "<cmd>lua require('gitsigns').diffthis()<cr>", { desc = "Diff This" })
vim.keymap.set("n", "<leader>gn", "<cmd>lua require('gitsigns').next_hunk()<cr>", { desc = "Next Hunk" })
